version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: /apps/api
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
