namespace HF {
  export function championToolbar(state:ViewState):string {
    const h=state.hybrid,c=state.champion,current=Boolean(h.result)&&!hybridDirty(h);
    const runState=h.busy?'Calculating':h.inputError?'Check inputs':current?(h.result?.run_id?'Saved result':'Bundled example'):'Setup ready';
    const local=c?.storage==='unavailable'?'Memory only':c?.lastSavedAt?'Locally saved':'Local-first';
    return `<div class="workbench-bar"><div class="workbench-status"><span class="status-beacon ${h.busy?'busy':''}"></span><span><strong>${escapeHTML(runState)}</strong><small>${escapeHTML(local)} · no cloud sync</small></span></div><div class="workbench-actions"><button class="btn quiet small" data-champion-action="guide">${icon('play',14)}<span>Quick start</span></button><button class="btn secondary small" data-champion-action="workspace">${icon('layers',14)}<span>Saved setups</span><b>${c?.saved.length??0}</b></button><button class="btn quiet small" data-nav="compare">${icon('activity',14)}<span>Compare</span><b>${h.compare.length}</b></button></div></div>${c?.notice?`<div class="workspace-notice" role="status">${icon('info',15)}<span>${escapeHTML(c.notice)}</span><button class="icon-button" data-champion-action="dismiss-notice" aria-label="Dismiss workspace notice">${icon('close',14)}</button></div>`:''}`;
  }
  export function workspaceDialog(state:ViewState):string {
    const c=state.champion!,h=state.hybrid;
    return `<div class="modal-copy workspace-dialog"><div class="workspace-summary"><span>${icon('layers',25)}</span><div><h3>Your experiments, within reach.</h3><p>Configurations stay in this browser. Calculated runs stay in your local Python database. Export files to move between devices.</p></div></div>${c.recoveryRaw?`<div class="notice warn"><span>The stored workspace is damaged or incompatible. It has been left untouched.</span></div><div class="h-actions"><button class="btn secondary" data-champion-action="recovery-export">Download recovery record</button><button class="btn quiet" data-champion-action="recovery-reset">Reset damaged cache</button></div>`:''}<form id="save-setup-form"><label class="field"><span>Name this setup</span><input name="setup_name" type="text" required maxlength="80" value="${escapeHTML((systemById(h.inputs.system_id).name+' / '+scenarioById(h.inputs.scenario_id).name).slice(0,80))}" autocomplete="off"></label><button class="btn primary" type="submit" ${h.busy||h.inputError||c.saved.length>=20||Boolean(c.recoveryRaw)?'disabled':''}>${icon('check',16)} Save current setup</button><p class="form-note">Up to 20 named setups. This saves inputs, not a new calculation.${h.inputError?' Correct the current input error first.':''}</p></form><div class="shelf-heading"><h3>${c.saved.length} saved ${c.saved.length===1?'setup':'setups'}</h3><button class="text-link" data-champion-action="export-workspace">Export workspace</button></div><div class="setup-list">${c.saved.length?c.saved.map(s=>`<article class="setup-row"><div class="setup-row-icon">${icon('layers',19)}</div><div class="setup-copy"><strong>${escapeHTML(s.name)}</strong><small>${escapeHTML(systemById(s.inputs.system_id).name)} · ${s.inputs.hours} h</small></div><div class="setup-actions"><button class="btn secondary small" data-load-setup="${s.id}" ${h.busy?'disabled':''}>Open</button><button class="icon-button" data-export-setup="${s.id}" aria-label="Export ${escapeHTML(s.name)}">${icon('download',16)}</button><button class="icon-button" data-delete-setup="${s.id}" aria-label="Delete ${escapeHTML(s.name)}">${icon('close',16)}</button></div></article>`).join(''):'<div class="shelf-empty"><strong>Begin with a reference case.</strong><p>Give your current inputs a name. You can return to them after changing a scenario.</p></div>'}</div><div class="notice"><span>${c.storage==='unavailable'?'Browser storage is unavailable. Your setups are in memory only: export before closing.':'Clearing browser data removes these shortcuts. It does not delete API runs or exported files.'}</span></div></div>`;
  }
  export function historyDialog(runs:RunRecord[]):string {
    return `<div class="modal-copy"><p>Latest 100 local runs. Each record contains exact inputs, results, timestamp and input hash. This is not a tamper-evident ledger.</p><label class="search-field run-search">${icon('search',16)}<input id="run-search" type="search" placeholder="Filter by model or run ID…" aria-label="Filter saved runs"></label><div id="run-results">${historyRows(runs,'')}</div></div>`;
  }
  export function historyRows(runs:RunRecord[],query:string):string {
    const q=query.toLowerCase().trim(),visible=runs.filter(r=>`${r.kind} ${r.id} ${r.created_at}`.toLowerCase().includes(q));
    return `<div class="history-count" role="status">${visible.length} saved ${visible.length===1?'run':'runs'}</div><div class="run-list">${visible.length?visible.map(r=>`<article class="run-row"><div class="setup-row-icon">${icon(r.kind==='hybrid'?'layers':'document',18)}</div><div class="setup-copy"><strong>${escapeHTML(r.kind==='hybrid'?'Hybrid energy screen':r.kind)}</strong><small>${escapeHTML(new Date(r.created_at).toLocaleString())}</small><code>${escapeHTML(r.id.slice(0,8))} · ${escapeHTML(r.input_hash.slice(0,12))}</code></div><div class="setup-actions">${r.kind==='hybrid'?`<button class="btn secondary small" data-restore-run="${escapeHTML(r.id)}">Open run</button>`:''}<button class="icon-button" data-run="${escapeHTML(r.id)}" aria-label="Download ${escapeHTML(r.kind)} run ${escapeHTML(r.id.slice(0,8))}">${icon('download',16)}</button></div></article>`).join(''):'<div class="shelf-empty"><h3>No matching runs yet.</h3><p>Calculate a scenario to create a record, or clear this filter.</p></div>'}</div>`;
  }
  export function commandDialog():string {
    return `<div class="command-dialog"><label class="command-input">${icon('search',22)}<input id="command-search" type="search" autocomplete="off" placeholder="Find a workspace, architecture or lesson…" aria-label="Search commands" role="combobox" aria-autocomplete="list" aria-expanded="true" aria-controls="command-results"></label><div id="command-results" role="listbox" aria-label="Commands">${commandResults('')}</div><div class="command-footer"><span><kbd>↑</kbd><kbd>↓</kbd> Navigate <kbd>Enter</kbd> Open</span><span><kbd>Esc</kbd> Close</span></div></div>`;
  }
  export function commandResults(query:string):string {
    const rows=commandEntries(query);
    return rows.length?rows.map((r,i)=>`<button class="command-option ${i===0?'active':''}" id="command-option-${i}" role="option" aria-selected="${i===0}" data-command-kind="${r.kind}" data-command-target="${r.target}"><span class="command-icon">${icon(r.icon,18)}</span><span><strong>${escapeHTML(r.label)}</strong><small>${escapeHTML(r.detail)}</small></span>${icon('arrow',16)}</button>`).join(''):'<div class="shelf-empty" role="status">No matches. Try “hospital”, “BESS”, “hydrogen” or “finance”.</div>';
  }
  export function quickStartDialog():string {
    return `<div class="modal-copy quick-start"><span class="eyebrow">YOUR FIRST REPRODUCIBLE EXPERIMENT</span><h3>What changes when the grid goes away?</h3><p>A hospital microgrid makes a useful first comparison. This is synthetic hourly energy adequacy, not a hospital safety assessment.</p><div class="guide-steps">${[
      ['Set the reference','Open Hospital islanding microgrid with the Reference day scenario. Save the setup with a meaningful name.'],
      ['Calculate and pin','Run the energy screen, inspect its assumptions, then use Pin to compare.'],
      ['Change one condition','Select Four-hour outage, run again, and pin the second result.'],
      ['Follow the evidence','Open Scenario compare. Check critical shortfall and both battery energy endpoints before interpreting cost.']
    ].map((s,i)=>`<article><span>${i+1}</span><div><strong>${s[0]}</strong><p>${s[1]}</p></div></article>`).join('')}</div><div class="h-actions"><button class="btn primary" data-champion-action="start-hospital">Open the reference case ${icon('arrow',16)}</button><button class="btn secondary" data-nav="lessons">Explore guided lessons</button></div><p class="form-note">A running local API is needed for new calculations. Preview mode still supports architecture exploration and self-checks.</p></div>`;
  }
}
