namespace HF {
  const E = escapeHTML;
  const green = '#d7ff84', teal = '#82cbbb', blue = '#9bacdf', gold = '#dfbd80';
  function tag(text: string, tone = ''): string { return `<span class="tag ${tone}">${E(text)}</span>`; }
  function heading(title: string, subtitle: string, extra = ''): string { return `<div class="section-heading"><div><h2>${E(title)}</h2><p>${E(subtitle)}</p></div>${extra}</div>`; }
  function metric(label: string, value: string, unit: string, caption: string, name: string, values: number[], tone = green): string {
    return `<article class="metric panel"><div class="metric-top"><span>${E(label)}</span>${icon(name,18)}</div><div class="metric-value">${E(value)} <small>${E(unit)}</small></div><div class="metric-foot"><span>${E(caption)}</span>${values.length>1?sparkline(values,tone):''}</div></article>`;
  }
  function stats(items: {label:string;value:string;hint?:string}[]): string { return `<div class="result-stats">${items.map(i=>`<div><span>${E(i.label)}</span><strong>${E(i.value)}</strong>${i.hint?`<small>${E(i.hint)}</small>`:''}</div>`).join('')}</div>`; }
  function notice(message: string, tone = ''): string { return `<div class="notice ${tone}">${icon(tone === 'warn'?'alert':'info',17)}<span>${E(message)}</span></div>`; }
  function warnings(result: {warnings:string[];run_id?:string}): string {
    return `<details class="method-details"><summary>${icon('shield',15)} Model boundaries & provenance ${icon('down',13)}</summary><div>${result.warnings.map(w=>`<p>${E(w)}</p>`).join('')}${result.run_id?`<p class="mono">Audit run · ${E(result.run_id)}</p>`:''}</div></details>`;
  }
  function field(name: string, label: string, value: unknown, opts: {min?:number;max?:number;step?:number;unit?:string} = {}): string {
    return `<label class="field"><span>${E(label)}</span><div class="input-unit"><input name="${E(name)}" type="number" value="${E(value)}" required ${opts.min!==undefined?`min="${opts.min}"`:''} ${opts.max!==undefined?`max="${opts.max}"`:''} step="${opts.step ?? 'any'}">${opts.unit?`<span>${E(opts.unit)}</span>`:''}</div></label>`;
  }
  function submit(state: ViewState, text: string): string { return `<button class="btn primary full" type="submit" ${!state.connected||state.busy?'disabled':''}>${icon(state.busy?'clock':'play',16)}${state.busy?'Calculating…':E(text)}</button>${!state.connected?'<p class="form-note">Snapshot preview. Start the Python API to run new calculations.</p>':''}`; }
  function legend(series: {name:string;color:string;dashed?:boolean}[]): string { return `<div class="legend">${series.map(s=>`<span><i style="background:${s.color}" class="${s.dashed?'dashed':''}"></i>${E(s.name)}</span>`).join('')}</div>`; }
  function modelBadge(): string { return tag('ILLUSTRATIVE MODEL','muted'); }
  function dispatchPlot(d: Dispatch, prices = false): string {
    const labels=d.schedule.map(r=>r.label), values=prices?[{name:'Import tariff',values:d.schedule.map(r=>r.import_eur_mwh),color:gold,area:true}]:[
      {name:'Site demand',values:d.schedule.map(r=>r.load_kw/1000),color:blue,dashed:true},
      {name:'Solar PV',values:d.schedule.map(r=>r.pv_kw/1000),color:green,area:true},
      {name:'Grid import',values:d.schedule.map(r=>r.grid_import_kw/1000),color:teal}];
    return legend(values)+lineChart(labels,values,{unit:prices?'EUR / MWh':'MW',height:244});
  }
  function projectTable(state: ViewState): string {
    const rows=filterProjects(state.data.portfolio,state.marketFilter,state.search);
    return `<div class="table-scroll"><table class="project-table"><thead><tr><th>Project</th><th>Market</th><th>Technology</th><th>Screening CAPEX</th><th>Stage</th><th>Review progress</th></tr></thead><tbody>${rows.length?rows.map((p,i)=>`<tr><td><button class="project-link" data-project="${E(p.id)}"><span class="project-icon tone-${i%3}">${icon(p.technology==='Wind'?'wind':p.technology==='BESS'?'battery':'sun',19)}</span><span><strong>${E(p.name)}</strong><small>${E(p.id)}</small></span></button></td><td><span class="country-code">${E(p.market)}</span></td><td>${E(p.technology)}</td><td>€${fmt(p.capex_meur,1)}m</td><td>${tag(p.stage,'muted')}</td><td><div class="progress-cell"><div class="progress"><i style="width:${p.progress}%"></i></div><span>${p.progress}%</span></div></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No projects match this filter.</td></tr>'}</tbody></table></div>`;
  }
  function overview(state: ViewState): string {
    const d=state.data, f=d.finance, s=d.dispatch, pv=d.pv;
    return `<section class="hero panel"><div class="hero-copy"><span class="eyebrow"><i></i> THE ENERGY INTELLIGENCE WORKSPACE</span><h2>Research with purpose.<br><em>Energy with an edge.</em></h2><p>Connect asset performance, storage economics and investment decisions in one evidence-led workspace.</p><div class="hero-actions"><button class="btn primary" data-nav="storage">Explore storage lab ${icon('arrow',17)}</button><button class="btn quiet" data-nav="council">Meet the council ${icon('diagonal',16)}</button></div><div class="hero-foot"><span>4 research pillars</span><b>·</b><span>6 market scenarios</span><b>·</b><span>Open by design</span></div></div>${energyOrb()}</section>
    <section class="metrics-grid">
    ${metric('Storage dispatch savings',money(s.savings_eur),' / day',`${fmt(s.savings_pct,1)}% · synthetic 24h case`,'battery',[],green)}
    ${metric('Project screening NPV',millions(f.npv_eur),'',`${fmt(f.irr_pct,1)}% IRR · assumed cash flows`,'briefcase',[],teal)}
    ${metric('Discounted solar LCOE',`€${fmt(pv.lcoe_eur_mwh,2)}`,'/ MWh',`${fmt(Number(d.defaults.pv.capacity_kwp)/1000,0)} MWp · independent PV scenario`,'sun',[],gold)}
    ${metric('Life-cycle carbon intensity',fmt(d.sustainability.intensity_gco2e_kwh,1),'gCO₂e/kWh','Screening inventory · not certified','leaf',[],blue)}
    </section>
    <div class="overview-grid"><section class="panel plot-panel">${heading('Every interval tells a story',`${d.markets.find(m=>m.code===d.market)?.name ?? d.market} · synthetic dispatch · ${fmt(s.power_kw/1000,1)} MW / ${fmt(s.capacity_kwh/1000,1)} MWh`, `<div class="segmented" aria-label="Chart view"><button data-chart="dispatch" class="${state.chartMode==='dispatch'?'active':''}" aria-pressed="${state.chartMode==='dispatch'}">Dispatch</button><button data-chart="prices" class="${state.chartMode==='prices'?'active':''}" aria-pressed="${state.chartMode==='prices'}">Tariff</button></div>`)}${dispatchPlot(s,state.chartMode==='prices')}</section>
    <section class="panel focus-panel">${heading('The decision signal','A return is not a credit decision.',icon('target',21))}<div class="decision-numbers"><div><span>PROJECT IRR</span><strong>${fmt(f.irr_pct,1)}<small>%</small></strong></div><span class="versus">≠</span><div><span>MINIMUM DSCR</span><strong class="amber">${fmt(f.minimum_dscr,2)}<small>×</small></strong></div></div><div class="risk-callout">${icon('alert',18)}<div><strong>${f.minimum_dscr===null?'Unlevered screening case':f.covenant_pass?'Modeled covenant clears the threshold':'Modeled debt-service covenant breach'}</strong><p>${f.minimum_dscr===null?'No debt service is modeled. Validate the operating case and all investment assumptions.':`NPV is ${f.npv_eur>=0?'positive':'negative'}; minimum DSCR ${f.covenant_pass?'meets':'falls below'} the ${fmt(f.dscr_covenant,2)}× covenant. Review every year, including augmentation.`}</p></div></div><div class="focus-bottom"><span>Level-payment debt capacity</span><strong>${millions(f.level_payment_debt_capacity_eur)}</strong></div><button class="text-link" data-nav="investment">Challenge the investment case ${icon('arrow',16)}</button></section></div>
    <section class="panel portfolio-panel">${heading('Opportunity workspace','Fictional projects for exploration. Not a live company pipeline.',`<button class="btn secondary small" data-action="export-portfolio">${icon('download',15)} Export</button>`)}<div class="table-tools"><label class="search-field">${icon('search',16)}<input id="project-search" type="search" placeholder="Search projects, technology or stage…" aria-label="Search projects" value="${E(state.search)}"></label><label class="select-wrap"><span class="sr-only">Filter portfolio by market</span><select id="portfolio-market"><option value="ALL">All markets</option>${d.markets.map(m=>`<option value="${m.code}" ${state.marketFilter===m.code?'selected':''}>${m.name}</option>`).join('')}</select></label></div><div id="project-table">${projectTable(state)}</div></section>
    <div class="pillar-strip">${[{name:'Operational efficiency',icon:'activity',desc:'See the signal.'},{name:'Predictive reliability',icon:'shield',desc:'Understand the risk.'},{name:'Sustainability',icon:'leaf',desc:'Measure the impact.'},{name:'Construction & pilots',icon:'flask',desc:'Test in the field.'}].map((p,i)=>`<button data-nav="${i===3?'pilots':'research'}"><span class="pillar-number">0${i+1}</span>${icon(p.icon,22)}<div><strong>${p.name}</strong><span>${p.desc}</span></div>${icon('diagonal',15)}</button>`).join('')}</div>`;
  }
  function storageView(state: ViewState): string {
    const d=state.data.dispatch,p=state.data.defaults.storage;
    return `<div class="page-intro"><span class="eyebrow">STORAGE LAB / BTM OPTIMIZATION</span><h2>Flexibility, made tangible.</h2><p>A mixed-integer dispatch model with physical constraints, transparent tariffs and a fair no-battery baseline.</p></div>${energyFlow()}
    <div class="lab-grid"><form class="panel form-panel" data-model="storage">${heading('Design your scenario','5 MW / 10 MWh liquid-cooled LFP reference.')}
    <div class="form-grid">${field('capacity_mwh','Energy capacity',Number(p.capacity_kwh)/1000,{min:.1,max:1000,step:.1,unit:'MWh'})}${field('power_mw','Power rating',Number(p.power_kw)/1000,{min:.1,max:500,step:.1,unit:'MW'})}${field('efficiency_pct','Round-trip efficiency',Number(p.round_trip_efficiency)*100,{min:1,max:100,step:.1,unit:'%'})}${field('wear','Discharge wear',p.wear_eur_per_kwh,{min:0,step:.001,unit:'€/kWh'})}${field('soc_min','Minimum SOC',Number(p.min_soc_fraction)*100,{min:0,max:99,unit:'%'})}${field('soc_max','Maximum SOC',Number(p.max_soc_fraction)*100,{min:1,max:100,unit:'%'})}${field('peak_charge','Peak charge per period',p.peak_charge_eur_per_kw_period,{min:0,unit:'€/kW'})}${field('grid_limit','Import limit',Number(p.grid_import_limit_kw)/1000,{min:.1,max:500,unit:'MW'})}</div>${notice('Hourly synthetic profile. Initial and terminal SOC are fixed at 50%; peak charges apply to this period only.')}${submit(state,'Optimize dispatch')}</form>
    <section class="panel plot-panel">${heading('The optimized day',`${d.solver} · ${d.solver_status}`,modelBadge())}${stats([{label:'Net savings',value:money(d.savings_eur),hint:`${d.duration_hours}h modeled period`},{label:'Discharge cycles',value:fmt(d.equivalent_discharge_cycles,2),hint:'AC discharge / nameplate kWh'},{label:'Terminal SOC',value:`${fmt(d.terminal_soc_kwh/1000,1)} MWh`,hint:'No free end-of-period energy'}])}${dispatchPlot(d)}<div class="cost-bridge"><div><span>No-battery cost</span><strong>${money(d.baseline_cost_eur)}</strong></div><span>→</span><div><span>Optimized cost + wear</span><strong>${money(d.optimized_cost_eur)}</strong></div><button class="btn secondary small" data-action="export-dispatch">${icon('download',15)} CSV</button></div>${warnings(d)}</section></div>
    <section class="panel plot-panel">${heading('Battery state of charge','Energy conservation, with bounded operating limits.')}${legend([{name:'State of charge',color:green}])}${lineChart(d.schedule.map(r=>r.label),[{name:'SOC',values:d.schedule.map(r=>r.soc_pct),color:green,area:true}],{height:200,unit:'%'})}</section>`;
  }
  function pvView(state: ViewState): string {
    const r=state.data.pv,p=state.data.defaults.pv;
    return `<div class="page-intro"><span class="eyebrow">PV ECONOMICS / DESIGN SCREENING</span><h2>Good projects start with sound assumptions.</h2><p>Discounted lifecycle costs, degraded generation and indicative land use. Yield and capture price remain explicit inputs.</p></div>
    <div class="metrics-grid">${metric('Discounted LCOE',`€${fmt(r.lcoe_eur_mwh,2)}`,'/ MWh','Consistent constant-money basis','sun',[],gold)}${metric('Total project CAPEX',millions(r.capex_eur),'','Nameplate capacity × unit cost','layers',[],teal)}${metric('Year-one generation',fmt(r.first_year_generation_mwh/1000,2),'GWh','After assumed curtailment','bolt',[],green)}${metric('Indicative land area',fmt(r.indicative_land_ha,1),'ha','Panel area / ground coverage','globe',[],blue)}</div>
    <div class="lab-grid"><form class="panel form-panel" data-model="pv">${heading('Project assumptions','A screening model, not an engineering design.')}<div class="form-grid">${field('capacity_mwp','PV capacity',Number(p.capacity_kwp)/1000,{min:.1,unit:'MWp'})}${field('yield','Specific yield',p.specific_yield_kwh_kwp,{min:1,max:2600,unit:'kWh/kWp'})}${field('capex','Unit CAPEX',p.capex_eur_kwp,{min:1,unit:'€/kWp'})}${field('opex','Annual OPEX',p.opex_eur_kwp_year,{min:0,unit:'€/kWp'})}${field('discount','Discount rate',Number(p.discount_rate)*100,{min:0,max:40,unit:'%'})}${field('capture','Capture price',p.capture_price_eur_mwh,{min:0,unit:'€/MWh'})}${field('curtailment','Curtailment',Number(p.curtailment_fraction)*100,{min:0,max:99,unit:'%'})}${field('gcr','Ground coverage',Number(p.ground_coverage_ratio)*100,{min:1,max:100,unit:'%'})}</div>${notice('30 years, 0.4% annual degradation and year-15 inverter replacement. Full inputs are included in exported evidence.')}${submit(state,'Evaluate PV economics')}</form>
    <section class="panel plot-panel">${heading('Yield across the project life','Annual generation after degradation.',modelBadge())}${stats([{label:'Project screening NPV',value:millions(r.npv_eur)},{label:'Panel count',value:fmt(r.panel_count)},{label:'Capture price',value:`€${fmt(r.capture_price_eur_mwh)}/MWh`}])}${legend([{name:'Net generation',color:gold}])}${lineChart(r.rows.map(x=>`Y${x.year}`),[{name:'Generation',values:r.rows.map(x=>x.generation_mwh/1000),color:gold,area:true}],{unit:'GWh',height:270})}${warnings(r)}</section></div>
    <section class="panel evidence-banner">${icon('document',30)}<div><h3>From screening to technical diligence</h3><p>Validate the layout, terrain, shading, DC/AC ratio, grid connection, EPC scope, warranties and site-specific yield before making a decision.</p></div><a class="btn secondary" href="https://re.jrc.ec.europa.eu/pvg_tools/en/" target="_blank" rel="noopener noreferrer">Open PVGIS ${icon('diagonal',15)}</a></section>`;
  }
  function researchView(state: ViewState): string {
    const d=state.data,p=d.defaults.reliability,c=d.defaults.sustainability;
    const pillars=[{name:'Operational efficiency',icon:'activity',copy:'Valorize asset data, normalize performance and surface drift before it becomes a persistent loss.',items:'Advanced KPIs / robust residuals / data provenance'},
      {name:'Predictive reliability',icon:'shield',copy:'Study failure risk with transparent reliability assumptions and a clear boundary between screening and diagnosis.',items:'Fault hypotheses / conditional risk / prognostics roadmap'},
      {name:'Sustainability',icon:'leaf',copy:'Track lifecycle emissions and keep ecological evidence distinct from carbon accounting.',items:'LCA inventory / counterfactual carbon / habitat baseline'},
      {name:'Construction & pilots',icon:'flask',copy:'Connect field instrumentation, experimental protocols and innovative construction methods.',items:'Field trials / instrumentation / evidence gates'}];
    return `<section class="research-cards">${pillars.map((p,i)=>`<article class="panel research-card"><div class="research-top"><span>0${i+1}</span>${icon(p.icon,27)}</div><h3>${p.name}</h3><p>${p.copy}</p><small>${p.items}</small></article>`).join('')}</section>
    <section class="panel plot-panel">${heading('A signal worth investigating','Synthetic performance residuals; first third used as a healthy baseline.',tag(`${d.drift.alert_count} flagged intervals`,'warn'))}${stats([{label:'Recent residual mean',value:`${fmt(d.drift.drift_pct,2)}%`},{label:'Robust baseline sigma',value:`${fmt(d.drift.sigma_fraction*100,2)}%`},{label:'Diagnostic status',value:'Review required'}])}${lineChart(d.drift.series.map(r=>String(r.index+1)),[{name:'Performance residual',values:d.drift.series.map(r=>r.residual_pct),color:teal,area:true}],{unit:'%',height:220})}${warnings(d.drift)}</section>
    <div class="two-columns"><form class="panel form-panel" data-model="reliability">${heading('Reliability lens','Conditional Weibull survival, not a field-trained RUL model.',icon('shield',22))}${stats([{label:`Failure probability over ${fmt(Number(d.defaults.reliability.horizon_hours))} h`,value:`${fmt(d.reliability.conditional_failure_pct,1)}%`},{label:'Median remaining life',value:`${fmt(d.reliability.conditional_median_remaining_hours)} h`}])}<div class="form-grid">${field('shape','Weibull shape',p.shape,{min:.01,step:.01})}${field('scale','Scale parameter',p.scale_hours,{min:1,unit:'h'})}${field('age','Current age',p.age_hours,{min:0,unit:'h'})}${field('horizon','Risk horizon',p.horizon_hours,{min:1,unit:'h'})}</div>${submit(state,'Evaluate reliability')}${warnings(d.reliability)}</form>
    <form class="panel form-panel" data-model="sustainability">${heading('Life-cycle carbon lens','Screening inventory with an explicit counterfactual.',icon('leaf',22))}${stats([{label:'Lifecycle intensity',value:`${fmt(d.sustainability.intensity_gco2e_kwh,1)} g/kWh`},{label:'Net counterfactual avoidance',value:`${fmt(d.sustainability.net_counterfactual_avoided_tco2e/1000,1)} ktCO₂e`}])}<div class="form-grid">${field('generation','Annual generation',Number(c.annual_generation_kwh)/1e6,{min:.01,unit:'GWh'})}${field('embodied','Embodied carbon',Number(c.embodied_kgco2e)/1000,{min:0,unit:'tCO₂e'})}${field('counterfactual','Counterfactual factor',Number(c.counterfactual_kgco2e_kwh)*1000,{min:0,unit:'gCO₂e/kWh'})}${field('operational','Annual operational carbon',Number(c.annual_operational_kgco2e)/1000,{min:0,unit:'tCO₂e'})}</div>${submit(state,'Evaluate carbon inventory')}${warnings(d.sustainability)}</form></div>`;
  }
  function marketsView(state: ViewState): string {
    const d=state.data;
    return `<div class="page-intro"><span class="eyebrow">MARKET INTELLIGENCE / EVIDENCE FIRST</span><h2>Six markets. No one-size-fits-all story.</h2><p>Customer value propositions are hypotheses to validate against actual site data, contracts and local rules.</p></div>${notice('This is a source registry and review workflow, not a live regulatory feed. No tariffs, exemptions or market-access permissions have been approved.','warn')}
    <section class="market-cards">${d.markets.map(m=>`<article class="panel market-card"><div class="market-top"><span class="country-emblem">${m.code}</span>${tag('Needs local review','warn')}</div><h3>${m.name}</h3><span class="market-segment">${m.segment}</span><p>${m.hypothesis}</p><div class="market-meta"><div><span>Tariff basis</span><strong>Illustrative EUR</strong></div><div><span>Effective / review date</span><strong>Not established</strong></div></div><a href="${safeURL(m.url)}" target="_blank" rel="noopener noreferrer" class="text-link">${E(m.regulator)} · primary source ${icon('diagonal',15)}</a></article>`).join('')}</section>
    <section class="panel plot-panel">${heading('The evidence stack','Official starting points. Data connectors are not enabled.',`<button class="btn secondary small" data-action="export-checklist">${icon('download',15)} Review checklist</button>`)}<div class="source-list">${d.sources.map(s=>`<a href="${safeURL(s.url)}" target="_blank" rel="noopener noreferrer"><span class="source-icon">${icon('database',22)}</span><div><strong>${E(s.name)}</strong><p>${E(s.scope)}</p></div>${tag(s.status.replaceAll('_',' '),'muted')}${icon('diagonal',17)}</a>`).join('')}</div>${notice('Great Britain is normalized to EUR only for the demo. Real analysis requires explicit GBP values, FX assumptions, taxes, network fees and settlement conventions.')}</section>`;
  }
  function forecastView(state: ViewState): string {
    const p=state.data.defaults.forecast,r=state.data.forecast,rows=r.rows.slice(0,state.forecastYears),last=rows[rows.length-1]!;
    return `<div class="page-intro"><span class="eyebrow">FORECAST STUDIO / SCENARIO EXPLORATION</span><h2>Price the uncertainty.</h2><p>A reproducible, mean-reverting scenario generator. Parameters are illustrative, not fitted to current forward curves.</p></div>
    <div class="lab-grid"><form class="panel form-panel" data-model="forecast">${heading('Shape a possible future','Annual prices · constant EUR / MWh')}<div class="form-grid">${field('base','Starting price',p.base_price_eur_mwh,{unit:'€/MWh'})}${field('target','Long-run price',p.long_run_price_eur_mwh,{unit:'€/MWh'})}${field('shock','Annual shock sigma',p.annual_shock_eur_mwh,{min:0,max:250,unit:'€/MWh'})}${field('reversion','Mean reversion',p.mean_reversion,{min:.01,max:1,step:.01})}${field('trend','Annual target trend',p.trend_eur_mwh_year,{unit:'€/MWh/y'})}${field('seed','Random seed',p.seed,{min:0,max:4294967295,step:1})}</div>${notice('1,500 paths over 20 years. Negative outcomes are allowed. Country selection is metadata, not an automatic calibration.')}${submit(state,'Generate price scenarios')}</form>
    <section class="panel plot-panel">${heading('A range, not a promise',`${fmt(r.paths)} simulated paths · seed ${r.seed}`,`<div class="segmented"><button data-horizon="10" class="${state.forecastYears===10?'active':''}" aria-pressed="${state.forecastYears===10}">10Y</button><button data-horizon="20" class="${state.forecastYears===20?'active':''}" aria-pressed="${state.forecastYears===20}">20Y</button></div>`)}${stats([{label:`${last.year} P10`,value:`€${fmt(last.p10_eur_mwh,1)}/MWh`},{label:`${last.year} P50`,value:`€${fmt(last.p50_eur_mwh,1)}/MWh`},{label:`${last.year} P90`,value:`€${fmt(last.p90_eur_mwh,1)}/MWh`}])}${legend([{name:'P10–P90 envelope',color:teal},{name:'P50 median',color:green}])}${lineChart(rows.map(x=>String(x.year)),[{name:'P10',values:rows.map(x=>x.p10_eur_mwh),color:teal,dashed:true},{name:'P50',values:rows.map(x=>x.p50_eur_mwh),color:green},{name:'P90',values:rows.map(x=>x.p90_eur_mwh),color:teal,dashed:true}],{unit:'EUR / MWh',height:290,band:[rows.map(x=>x.p10_eur_mwh),rows.map(x=>x.p90_eur_mwh)]})}${warnings(r)}</section></div>`;
  }
  function investmentView(state: ViewState): string {
    const r=state.data.finance,p=state.data.defaults.finance,m=state.data.acquisition,q=state.data.defaults.acquisition;
    const debtRows=r.rows.filter(x=>x.dscr!==null);
    return `<div class="page-intro"><span class="eyebrow">INVESTMENT DESK / UNDERWRITE THE DOWNSIDE</span><h2>The return is only the beginning.</h2><p>Screen project value, challenge debt service and separate enterprise value from equity value.</p></div>
    <div class="metrics-grid">${metric('Unlevered project IRR',fmt(r.irr_pct,1),'%','Pre-tax · nominal assumptions','chart',[],green)}${metric('Project NPV',millions(r.npv_eur),'','At the selected discount rate','briefcase',[],teal)}${metric('Minimum DSCR',fmt(r.minimum_dscr,2),'×',r.minimum_dscr===null?'No debt service':`${r.covenant_pass?'Meets':'Below'} ${fmt(r.dscr_covenant,2)}× covenant`,'shield',debtRows.map(x=>x.dscr??0),gold)}${metric('Simple payback',fmt(r.payback_years,1),'years','First undiscounted cash-flow crossing','clock',[],blue)}</div>
    ${r.covenant_pass===false?notice('Covenant breach under the selected debt structure. Review augmentation funding, leverage, contract terms and downside revenue before investment approval.','warn'):notice('This screen is not an investment approval. Verify source data, taxes, covenants and market eligibility.')}
    <div class="lab-grid"><form class="panel form-panel" data-model="finance">${heading('Project-finance assumptions','Independent from the daily storage example.')}<div class="form-grid">${field('capex','Upfront CAPEX',Number(p.capex_eur)/1e6,{min:.01,unit:'€m'})}${field('margin','Annual gross margin',Number(p.annual_gross_margin_eur)/1000,{min:0,unit:'€k'})}${field('opex','Annual OPEX',Number(p.annual_opex_eur)/1000,{min:0,unit:'€k'})}${field('discount','Discount rate',Number(p.discount_rate)*100,{min:0,max:40,unit:'%'})}${field('debt','Debt fraction',Number(p.debt_fraction)*100,{min:0,max:95,unit:'%'})}${field('interest','Debt interest',Number(p.debt_interest_rate)*100,{min:0,max:30,unit:'%'})}${field('merchant','Merchant margin factor',Number(p.merchant_margin_factor)*100,{min:0,max:200,unit:'%'})}${field('contracted','Contracted share',Number(p.contracted_fraction)*100,{min:0,max:100,unit:'%'})}${field('augmentation','Augmentation cost',Number(p.augmentation_cost_eur)/1000,{min:0,unit:'€k'})}${field('aug_year','Augmentation year',p.augmentation_year,{min:1,max:20,step:1})}</div>${submit(state,'Evaluate investment case')}</form>
    <section class="panel plot-panel">${heading('Debt-service resilience','CFADS includes augmentation before debt service.',modelBadge())}${legend([{name:'DSCR',color:teal},{name:'Covenant',color:gold,dashed:true}])}${lineChart(debtRows.map(x=>`Y${x.year}`),[{name:'DSCR',values:debtRows.map(x=>x.dscr??0),color:teal,area:true},{name:'Covenant',values:debtRows.map(()=>r.dscr_covenant),color:gold,dashed:true}],{unit:'×',height:260})}${stats([{label:'Level-payment debt capacity',value:millions(r.level_payment_debt_capacity_eur),hint:'Worst debt-year CFADS / covenant'},{label:'Financing approach',value:'Level annuity',hint:'No debt sculpting or reserve model'}])}${warnings(r)}</section></div>
    <div class="two-columns"><form class="panel form-panel" data-model="acquisition">${heading('M&A screening','Technology-neutral enterprise-value screen.')}<div class="form-grid">${field('ev','Enterprise value',Number(q.enterprise_value_eur)/1e6,{min:.01,unit:'€m'})}${field('ebitda','Annual EBITDA',Number(q.annual_ebitda_eur)/1e6,{min:.01,unit:'€m'})}${field('net_debt','Net debt',Number(q.net_debt_eur)/1e6,{min:0,unit:'€m'})}${field('maintenance','Maintenance CAPEX',Number(q.annual_maintenance_capex_eur)/1000,{min:0,unit:'€k/y'})}</div>${submit(state,'Screen acquisition')}</form>
    <section class="panel plot-panel">${heading('Valuation, with context','PV, wind and BESS require additional technical diligence.')}${stats([{label:'EV / EBITDA',value:`${fmt(m.ev_ebitda,2)}×`},{label:'Implied equity value',value:millions(m.implied_equity_value_eur)}])}${stats([{label:'Screening enterprise DCF',value:millions(m.screening_dcf_eur)},{label:'DCF minus asking EV',value:millions(m.valuation_gap_eur)}])}${warnings(m)}</section></div>`;
  }
  function pilotsView(state: ViewState): string {
    const stages: Pilot['status'][]=['planned','instrumenting','running','validated'];
    return `<div class="page-intro intro-with-action"><div><span class="eyebrow">CONSTRUCTION & PILOTS / FIELD EVIDENCE</span><h2>Make the next experiment count.</h2><p>Track instruments, hypotheses and evidence through explicit delivery gates.</p></div><button class="btn secondary" data-action="export-pilots">${icon('download',16)} Export register</button></div>${notice('All pilot records are fictional. “Validated” describes a simulated workflow state, not a real field result.')}
    <section class="pilot-board">${stages.map((stage,i)=>`<div class="board-column"><div class="board-heading"><span><i class="stage-dot stage-${i}"></i>${E(stage[0]!.toUpperCase()+stage.slice(1))}</span><b>${state.data.pilots.filter(x=>x.status===stage).length}</b></div>${state.data.pilots.filter(x=>x.status===stage).map(p=>`<article class="panel pilot-card"><div class="pilot-card-top"><span class="mono">${p.id}</span>${tag(p.pillar,'muted')}</div><h3>${E(p.title)}</h3><p>${E(p.target)}</p><div class="pilot-instrument">${icon('activity',17)}<span>${E(p.instrument)}</span></div><div class="pilot-owner"><span class="avatar small-avatar">${E(p.owner.slice(0,1))}</span><div><strong>${E(p.owner)}</strong><small>${E(p.site)}</small></div></div><button class="btn secondary small full" data-pilot="${p.id}">Review evidence ${icon('arrow',15)}</button></article>`).join('')}<div class="board-hint">${['Define the hypothesis and acceptance criteria.','Confirm calibration, safe installation and logging.','Collect observations against the agreed protocol.','Review evidence and record the limitations.'][i]}</div></div>`).join('')}</section>
    <section class="panel evidence-banner">${icon('shield',28)}<div><h3>Evidence before a status change</h3><p>Every update requires a note and is recorded in SQLite with the old state, new state and timestamp. No dashboard action operates equipment.</p></div></section>`;
  }
  function councilView(state: ViewState): string {
    const c=state.data.council;
    return `<div class="page-intro"><span class="eyebrow">AGENT COUNCIL / MULTIDISCIPLINARY REVIEW</span><h2>Better questions. Stronger decisions.</h2><p>Eight specialists challenge the evidence. An independent critic reconciles the findings. You remain the decision-maker.</p></div>
    <section class="council-topology ${state.busy?'working':''}">${[{name:'Storage engineer',icon:'battery'},{name:'Investment analyst',icon:'briefcase'},{name:'Market reviewer',icon:'globe'},{name:'Sustainability reviewer',icon:'leaf'},{name:'Hybrid architect',icon:'layers'},{name:'Learning designer',icon:'document'},{name:'Accessibility reviewer',icon:'shield'},{name:'Reproducibility reviewer',icon:'code'}].map((r,i)=>`<div class="council-node"><span class="agent-symbol agent-${i}">${icon(r.icon,25)}</span><strong>${r.name}</strong><small>Specialist review</small></div>`).join('')}<span class="council-arrow">→</span><div class="council-node critic"><span class="agent-symbol">${icon('sparkles',27)}</span><strong>Committee critic</strong><small>Challenge & synthesis</small></div></section>
    <div class="lab-grid"><form class="panel form-panel" data-model="council">${heading('Commission a review','Default market cases plus an explicitly selected saved hybrid run.')}<label class="field"><span>Attach saved hybrid evidence</span><select name="hybrid_run_id"><option value="">No hybrid run · default cases only</option>${state.hybrid.result?.run_id?`<option value="${E(state.hybrid.result.run_id)}">Current saved run · ${E(systemById(state.hybrid.result.system_id).name)}</option>`:''}${state.hybrid.compare.filter(x=>x.result.run_id&&x.id!==state.hybrid.result?.run_id).map(x=>`<option value="${E(x.id)}">${E(x.name)}</option>`).join('')}</select></label><label class="field"><span>Research brief</span><textarea name="brief" rows="6" required minlength="8" maxlength="6000">${E(c.reviewed_brief)}</textarea></label><label class="field"><span>Execution mode</span><select name="mode" id="council-mode"><option value="local">Local · deterministic checklist</option><option value="openai">OpenAI · actual multi-agent review</option></select></label><div id="external-consent" hidden><label class="field"><span>Server admin key (not stored in browser)</span><input name="admin_key" type="password" autocomplete="off"></label><label class="check-field"><input name="consent" type="checkbox">I consent to sending this brief and synthetic evidence to OpenAI. API usage may be billed.</label></div>${notice('Local mode is a fixed-scope, rule-based review—not an LLM. OpenAI mode requires server configuration and explicit consent.')}${submit(state,'Run council review')}</form>
    <section class="panel council-decision">${heading('The committee perspective',c.mode==='local'?'Deterministic checklist · no LLM used':'AI-generated review · human verification required',tag(c.mode==='local'?'LOCAL MODE':'OPENAI MODE',c.mode==='local'?'muted':'positive'))}<div class="decision-symbol">${icon('sparkles',30)}</div><h3>${E(c.decision.recommendation)}</h3><div class="council-actions"><span class="eyebrow">EVIDENCE TO CLOSE</span>${c.decision.next_actions.map((a,i)=>`<div><span>0${i+1}</span><p>${E(a)}</p></div>`).join('')}</div><button class="btn secondary small" data-action="export-council">${icon('download',16)} Export review</button></section></div>
    <section class="two-columns review-grid">${c.reviews.map((r,i)=>`<article class="panel review-card"><div class="review-heading"><span class="agent-symbol agent-${i}">${icon(['battery','briefcase','globe','leaf','layers','document','shield','code'][i]??'sparkles',21)}</span><h3>${E(r.agent)}</h3></div><p>${E(r.summary)}</p><div class="review-risk"><strong>Challenge</strong>${r.risks.map(x=>`<p>${E(x)}</p>`).join('')}</div><small>Required evidence</small>${r.required_evidence.map(x=>`<p>${E(x)}</p>`).join('')}</article>`).join('')}</section>${warnings(c)}`;
  }
  export function content(state: ViewState): string {
    const views: Record<Page,(s:ViewState)=>string> = {hybrid:hybridView,lessons:lessonsView,compare:compareView,overview,storage:storageView,pv:pvView,research:researchView,markets:marketsView,forecast:forecastView,investment:investmentView,pilots:pilotsView,council:councilView};
    return views[state.page](state);
  }
  export function shell(state: ViewState): string {
    const page=PAGES.find(p=>p.id===state.page)!;
    return `<a class="skip-link" href="#main-content">Skip to content</a><aside class="sidebar" id="sidebar"><a class="brand" href="#overview" aria-label="HelioForge command centre">${brandMark()}<div>helioforge<span>ENERGY INTELLIGENCE</span></div></a><button type="button" class="workspace-picker" data-champion-action="workspace" aria-label="Open saved setups"><span class="workspace-logo">${icon('layers',18)}</span><div>Research workspace<small>Saved setups & local recovery</small></div>${icon('down',13)}</button><nav aria-label="Main navigation">${PAGES.map(p=>`${p.group?`<p class="nav-group">${p.group}</p>`:''}<button data-nav="${p.id}" class="nav-item ${state.page===p.id?'selected':''}" ${state.page===p.id?'aria-current="page"':''}>${icon(p.icon,18)}<span>${p.title}</span>${p.id==='council'?'<span class="nav-badge">8+1</span>':''}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="open-source-card">${icon('code',20)}<strong>Built to be questioned.</strong><p>Open models. Visible assumptions.<br>Evidence you can inspect.</p><button data-action="methodology" class="text-link">Explore methodology ${icon('diagonal',13)}</button></div><div class="profile"><span class="avatar">HF</span><div>Energy R&D team<small>Champion · local edition</small></div><span class="presence"></span></div></div></aside>
    <div class="app-main"><header class="topbar"><div class="breadcrumb"><button class="icon-button mobile-menu" data-action="menu" aria-label="Toggle navigation" aria-controls="sidebar" aria-expanded="false">${icon('menu',21)}</button><span>Workspace</span>${icon('arrow',12)}<strong>${page.title}</strong></div><div class="topbar-right"><button class="command-trigger" data-champion-action="commands" aria-label="Search commands and architectures">${icon('search',16)}<span>Find anything</span><kbd>Ctrl K</kbd></button><button class="connection-chip ${state.connected?'online':''}" data-action="reconnect" title="Reconnect to the local API"><i></i>${state.connected?'API connected':'Snapshot preview'}</button><span class="topbar-divider"></span><button class="icon-button" data-action="motion" aria-label="${state.motionOff?'Enable':'Reduce'} animations" aria-pressed="${state.motionOff}">${icon(state.motionOff?'play':'pause',16)}</button><button class="icon-button" data-action="history" aria-label="Open analysis history">${icon('clock',19)}</button><span class="avatar top-avatar">HF</span></div></header>
    <main id="main-content" tabindex="-1"><div class="page-heading"><div><div class="page-kicker">HELIOFORGE / HYBRID ENERGY WORKBENCH</div><h1>${page.title}<span class="beta-label">CHAMPION · 0.3</span></h1><p>${page.subtitle}</p></div><div class="page-tools">${['hybrid','lessons','compare'].includes(state.page)?'':`<label class="select-wrap context-select">${icon('globe',16)}<span class="sr-only">Analysis market</span><select id="context-market" ${state.busy?'disabled':''}>${state.data.markets.map(m=>`<option value="${m.code}" ${m.code===state.data.market?'selected':''}>${m.name}</option>`).join('')}</select></label>`}<button class="btn secondary" data-action="export-evidence">${icon('download',16)}<span>Export evidence</span></button></div></div><div class="data-ribbon"><span><i></i> SYNTHETIC DATA</span><p>Illustrative scenarios, not live market data or investment advice.</p><button data-action="methodology">Model boundaries ${icon('diagonal',13)}</button></div><div id="champion-toolbar">${championToolbar(state)}</div><div id="page-content">${content(state)}</div><footer><span>${brandMark()} helioforge <b>·</b> Open energy intelligence</span><span>Transparent by design. Human decisions, always.</span></footer></main></div><div id="toast" class="toast" role="status" aria-live="polite"></div><div id="celebration" class="celebration" aria-hidden="true"></div><dialog id="modal" aria-labelledby="modal-title"></dialog>`;
  }
  export function updateProjectTable(state: ViewState): void { const t=document.getElementById('project-table'); if(t)t.innerHTML=projectTable(state); }
}
